# Generated by Django 3.2.6 on 2021-08-29 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('branch_name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=11)),
                ('open_time', models.CharField(max_length=5, null=True)),
                ('close_time', models.CharField(max_length=5, null=True)),
                ('business_license_number', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'branch',
            },
        ),
    ]
