# Generated by Django 3.2.6 on 2021-08-29 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('origin', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'ingredient',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('image', models.CharField(max_length=255)),
                ('price', models.IntegerField()),
                ('register_date', models.DateTimeField(auto_now_add=True)),
                ('menu_info', models.CharField(max_length=255, null=True)),
                ('allergy_ingredient', models.IntegerField()),
                ('branch_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='branches.branch')),
                ('ingredient', models.ManyToManyField(to='menus.Ingredient')),
            ],
            options={
                'db_table': 'menu',
            },
        ),
    ]
