# Generated by Django 3.2.6 on 2021-08-29 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='branch_id',
            new_name='branch',
        ),
    ]
