# Generated by Django 3.2.6 on 2021-08-29 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('menus', '0002_rename_branch_id_menu_branch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='branch',
            new_name='branch_id',
        ),
    ]
